### PR TITLE
finish webspeech network debug

### LINKED ISSUE #89: Webspeech Network Error
When webspeech throws a network error, the webspeech provider goes into the unexpected error state. Instead it should notify the user and retry after some timeout (exponential backoff?).

Image

### PR DESCRIPTION
**Pull request by Yuchuan-Tsai**
## Summary
This pr potentially solves the problem of network error bug and add reconnecting feature after network error happens in standalone-webapp.

### Error handling
* Network errors are now handled explicitly in the WebSpeech error handler.
* A reconnect process is triggered when a network error occurs.

### Updated WebSpeech UI:
* Modal now shows a reconnecting state during network retry.
* Status icon/tooltip now reflects network reconnecting status.

## Potential Reason of the bug
Previously, network errors could push the provider into a generic error experience without clear retry-state feedback.
Now users are informed of reconnecting progress and transient network issues recover automatically.

## Scope
apps/standalone-webapp WebSpeech provider + related status UI only.
No backend/API contract changes.

### CODE REVIEW

File: apps/standalone-webapp/src/features/transcription-providers/services/providers/webspeech/services/webspeech-provider.ts [hunk 1]
```diff
@@ -22,13 +25,23 @@ export class WebspeechProvider
   private _recognition: SpeechRecognition | null = null;
   private _finalizedResultCount = 0;
   private _providerIsStarted = false;
-  private readonly _microphoneService: MicrophoneService;
+  // private readonly _microphoneService: MicrophoneService;
```
Comment (bennettrwu) [inline apps/standalone-webapp/src/features/transcription-providers/services/providers/webspeech/services/webspeech-provider.ts]: This got uncommented, but then line 32 redefines it. Can you remove the redefinition and uncomment this? Otherwise, everything else looks good.

**Review by bennettrwu — CHANGES_REQUESTED** [review]

**Review by bennettrwu — APPROVED** [review]
